---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deploy
  labels:
    app: whoami
spec:
  replicas: 4
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
        env: canary
    spec:
      containers:
      - name: whoami
        image: acrdemo5.azurecr.io/whoami:v1
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: kama-kama
---
kind: Service
apiVersion: v1
metadata:
  name: whoami
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: whoami

